### ISSUE TITLE
Auto deletion of old records

### ISSUE THREAD

**Issue by domoticos** [runvnc/timequerylog#1]
First, thank you for this module! Nice work!
Do you consider auto deletion of old records after some time? A config option to delete records older than some time (e.g. one year)? This would be a nice feature preventing the situation to fill disk capacity after several years of intensive logs storage (its not hard to do that on Raspberry like boards with several gigs flash/eMMC).

**Comment by runvnc** [comment]
Thanks, useful feature idea.  I will see if I can add that.

**Comment by runvnc** [comment]
I added a `deleteOldDays` config option, see the `config()` description in the second half of the readme.

**Comment by domoticos** [comment]
Wow, that was quick! Thank you!
